--- 
kind: pipeline
name: LolzBuilder
steps: 
  - 
    commands:
      - "bash lolzkernel.sh"
    environment: 
      GITHUB_TOKEN: 
        from_secret: github_token
      TG_BOT_TOKEN: 
        from_secret: tg_bot_token
    image: "gengkapak/impish:latest"
    name: LOLZ_Builder
    trigger: 
      branch: 
        - master
