--- 
kind: pipeline
name: LolzBuilder
steps: 
  - 
    commands:
      - export DEBIAN_FRONTEND=noninteractive
      - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
      - ln -sf  /usr/share/zoneinfo/Asiab/Kolkata /etc/localtime
      - apt-get install -y tzdata
      - dpkg-reconfigure --frontend noninteractive tzdata
      - "bash lolzkernel.sh"
    environment: 
      GITHUB_TOKEN: 
        from_secret: github_token
      TG_BOT_TOKEN: 
        from_secret: tg_bot_token
    image: "ubuntu:21.10"
    name: LOLZ_Builder
    trigger: 
      branch: 
        - master
