--- 
kind: pipeline
name: LolzClang
steps: 
  - 
    commands:
      - "apt-get -y update && apt-get -y upgrade && DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends bc bison binutils-dev build-essential ca-certificates ccache clang cmake curl file flex git lld libelf-dev libssl-dev make ninja-build patchelf python3-dev texinfo u-boot-tools xz-utils zlib1g-dev"
      - "bash lolzkernel.sh"
    environment: 
      GITHUB_TOKEN: 
        from_secret: github_token
      TG_BOT_TOKEN: 
        from_secret: tg_bot_token
      TG_CHATID: 
        from_secret: tg_chatid
    image: "ubuntu:latest"
    name: clang_builder
    trigger: 
      branch: 
        - master
