#kurnal
version: 2.1
jobs:
  compile:
   docker:
      - image: jprimero15/archlinux-docker:latest
   steps:
      - run:
          command: |
            wget https://raw.githubusercontent.com/Jprimero15/LOLZ_Kernel_Builder/4.19_public/lolzkernel.sh
            bash lolzkernel.sh
          no_output_timeout : 5h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile 
