#kurnal
version: 2.1
jobs:
  compile:
   docker:
      - image: jprimero15/archlinux-docker:latest
   steps:
      - run:
          command: |
            bash lokzkernel.sh
          no_output_timeout : 5h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile 
