name: LOLZ Builder k4.19

on:
  push:
    branches:
      - 4.19_public

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: LOLZ Builder k4.19 working
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_CHATID: ${{ secrets.TG_CHATID }}
      run: |
        bash lolzkernel.sh
