name: LOLZ HLTE Builder

on:
  push:
    branches:
      - hlte-test

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: jprimero15/archlinux-docker:latest

    steps:
    - uses: actions/checkout@v4
    - name: LOLZ HLTE Builder working
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_CHATID: ${{ secrets.TG_CHATID }}
      run: |
        fastfetch
        bash lolzkernel.sh
