name: LOLZ Builder k4.19

on:
  push:
    branches:
      - 4.19_public

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: jprimero15/archlinux-docker:latest

    steps:
    - name: Check Out v3
      uses: actions/checkout@v3     
        
    - name: mi439 kernel builder working
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_CHATID: ${{ secrets.TG_CHATID }}
      run: |
        bash lolzkernel.sh
