name: LOLZ Builder

on:
  push:
    branches:
      - hlte-test

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            binutils \
            bc \
            bison \
            flex \
            cpio \
            curl \
            rsync \
            python3 \
            libssl-dev \
            libelf-dev

      - name: LOLZ Builder working
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHATID: ${{ secrets.TG_CHATID }}
        run: |
          chmod +x lolzkernel.sh
          bash lolzkernel.sh
