name: LOLZ Builder k4.19

on:
  push:
    branches:
      - 4.19_public

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Check Out v3
      uses: actions/checkout@v3

    - name: Configure builder
      shell: bash
      run: |

         echo "::group:: Installing Building Depend Packages"
         sudo apt-get update
         sudo apt-get install --no-install-recommends -y libelf-dev libncurses-dev binutils-dev binutils binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi git ccache automake flex lzop bison gperf build-essential zip curl g++-multilib liblz4-tool make libssl-dev policycoreutils bc unzip device-tree-compiler python3 aria2      
         sudo find /usr/ -name *bfd*
         gcc -v && ld -v
         echo "::endgroup::"

         echo "::group:: Setting Up Swap"
         export SWAP_FILE=$(swapon --show=NAME | tail -n 1)
         sudo swapoff $SWAP_FILE
         sudo rm $SWAP_FILE
         sudo fallocate -l 24G $SWAP_FILE
         sudo chmod 600 $SWAP_FILE
         sudo mkswap $SWAP_FILE
         sudo swapon $SWAP_FILE
         echo "::endgroup::"
        
    - name: mi439 kernel builder working
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_CHATID: ${{ secrets.TG_CHATID }}
      shell: bash
      run: |
        bash lolzkernel.sh
