name: LOLZ Builder k4.19

on:
  push:
    branches:
      - 4.19_public

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    container:
      image: panchajanya1999/archlinux:latest
    
    steps:
    - name: Check Out v4
      uses: actions/checkout@v4

    - name: Configure builder
      shell: bash
      run: |
         echo "::group:: Installing some archlinux Packages"
         pacman -S --noconfirm aarch64-linux-gnu-binutils arm-none-eabi-binutils aarch64-linux-gnu-gcc neofetch
         gcc -v && ld -v && neofetch
         echo "::endgroup::"

         echo "::group:: Setting Up Swap"
         export SWAP_FILE=$(swapon --show=NAME | tail -n 1)
         sudo swapoff $SWAP_FILE
         sudo rm $SWAP_FILE
         sudo fallocate -l 24G $SWAP_FILE
         sudo chmod 600 $SWAP_FILE
         sudo mkswap $SWAP_FILE
         sudo swapon $SWAP_FILE
         echo "::endgroup::"
        
    - name: mi439 kernel builder working
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_CHATID: ${{ secrets.TG_CHATID }}
      shell: bash
      run: |
        bash lolzkernel.sh
